export const PortugalDistricts = [
	{ district: 'Aveiro', city: 'Aveiro' },
	{ district: 'Aveiro', city: 'Águeda' },
	{ district: 'Aveiro', city: 'Albergaria-a-Velha' },
	{ district: 'Aveiro', city: 'Anadia' },
	{ district: 'Aveiro', city: 'Esmoriz' },
	{ district: 'Aveiro', city: 'Estarreja' },
	{ district: 'Aveiro', city: 'Gafanha da Nazaré' },
	{ district: 'Aveiro', city: 'Ílhavo' },
	{ district: 'Aveiro', city: 'Oliveira de Azeméis' },
	{ district: 'Aveiro', city: 'Oliveira do Bairro' },
	{ district: 'Aveiro', city: 'Ovar' },
	{ district: 'Aveiro', city: 'Santa Maria da Feira' },
	{ district: 'Aveiro', city: 'São João da Madeira' },
	{ district: 'Aveiro', city: 'Sever do Vouga' },
	{ district: 'Aveiro', city: 'Vale de Cambra' },

	{ district: 'Beja', city: 'Beja' },
	{ district: 'Beja', city: 'Castro Verde' },
	{ district: 'Beja', city: 'Moura' },
	{ district: 'Beja', city: 'Serpa' },

	{ district: 'Braga', city: 'Barcelos' },
	{ district: 'Braga', city: 'Braga' },
	{ district: 'Braga', city: 'Esposende' },
	{ district: 'Braga', city: 'Fafe' },
	{ district: 'Braga', city: 'Guimarães' },
	{ district: 'Braga', city: 'Vila Nova de Famalicão' },
	{ district: 'Braga', city: 'Vizela' },

	{ district: 'Bragança', city: 'Bragança' },
	{ district: 'Bragança', city: 'Macedo de Cavaleiros' },
	{ district: 'Bragança', city: 'Miranda do Douro' },
	{ district: 'Bragança', city: 'Mirandela' },
	{ district: 'Bragança', city: 'Mogadouro' },
	{ district: 'Bragança', city: 'Torre de Moncorvo' },
	{ district: 'Bragança', city: 'Vila Flor' },
	{ district: 'Bragança', city: 'Vila Nova de Foz Côa' },

	{ district: 'Castelo Branco', city: 'Castelo Branco' },
	{ district: 'Castelo Branco', city: 'Covilhã' },
	{ district: 'Castelo Branco', city: 'Fundão' },
	{ district: 'Castelo Branco', city: 'Sertã' },

	{ district: 'Coimbra', city: 'Arganil' },
	{ district: 'Coimbra', city: 'Cantanhede' },
	{ district: 'Coimbra', city: 'Coimbra' },
	{ district: 'Coimbra', city: 'Figueira da Foz' },
	{ district: 'Coimbra', city: 'Lousã' },
	{ district: 'Coimbra', city: 'Mealhada' },
	{ district: 'Coimbra', city: 'Miranda do Corvo' },
	{ district: 'Coimbra', city: 'Oliveira do Hospital' },
	{ district: 'Coimbra', city: 'Pampilhosa da Serra' },
	{ district: 'Coimbra', city: 'Penacova' },
	{ district: 'Coimbra', city: 'Penela' },
	{ district: 'Coimbra', city: 'Pombal' },
	{ district: 'Coimbra', city: 'Soure' },

	{ district: 'Évora', city: 'Borba' },
	{ district: 'Évora', city: 'Estremoz' },
	{ district: 'Évora', city: 'Évora' },
	{ district: 'Évora', city: 'Montemor-o-Novo' },
	{ district: 'Évora', city: 'Reguengos de Monsaraz' },
	{ district: 'Évora', city: 'Vendas Novas' },
	{ district: 'Évora', city: 'Vila Viçosa' },

	{ district: 'Algarve', city: 'Albufeira' },
	{ district: 'Algarve', city: 'Faro' },
	{ district: 'Algarve', city: 'Lagoa' },
	{ district: 'Algarve', city: 'Lagos' },
	{ district: 'Algarve', city: 'Loulé' },
	{ district: 'Algarve', city: 'Olhão' },
	{ district: 'Algarve', city: 'Portimão' },
	{ district: 'Algarve', city: 'Quarteira' },
	{ district: 'Algarve', city: 'Silves' },
	{ district: 'Algarve', city: 'Tavira' },
	{ district: 'Algarve', city: 'Vila Real de Santo António' },

	{ district: 'Guarda', city: 'Gouveia' },
	{ district: 'Guarda', city: 'Guarda' },
	{ district: 'Guarda', city: 'Mêda' },
	{ district: 'Guarda', city: 'Pinhel' },
	{ district: 'Guarda', city: 'Sabugal' },
	{ district: 'Guarda', city: 'Seia' },
	{ district: 'Guarda', city: 'Trancoso' },

	{ district: 'Leiria', city: 'Alcobaça' },
	{ district: 'Leiria', city: 'Batalha' },
	{ district: 'Leiria', city: 'Caldas da Rainha' },
	{ district: 'Leiria', city: 'Leiria' },
	{ district: 'Leiria', city: 'Marinha Grande' },
	{ district: 'Leiria', city: 'Nazaré' },
	{ district: 'Leiria', city: 'Pedrógão Grande' },
	{ district: 'Leiria', city: 'Peniche' },
	{ district: 'Leiria', city: 'Pombal' },
	{ district: 'Leiria', city: 'Porto de Mós' },
	{ district: 'Leiria', city: 'Tomar' },

	{ district: 'Lisboa', city: 'Agualva-Cacém' },
	{ district: 'Lisboa', city: 'Alverca do Ribatejo' },
	{ district: 'Lisboa', city: 'Amadora' },
	{ district: 'Lisboa', city: 'Lisboa' },
	{ district: 'Lisboa', city: 'Loures' },
	{ district: 'Lisboa', city: 'Odivelas' },
	{ district: 'Lisboa', city: 'Oeiras' },
	{ district: 'Lisboa', city: 'Póvoa de Santa Iria' },
	{ district: 'Lisboa', city: 'Queluz' },
	{ district: 'Lisboa', city: 'Sacavém' },
	{ district: 'Lisboa', city: 'Sintra' },
	{ district: 'Lisboa', city: 'Vila Franca de Xira' },

	{ district: 'Portalegre', city: 'Campo Maior' },
	{ district: 'Portalegre', city: 'Elvas' },
	{ district: 'Portalegre', city: 'Ponte de Sor' },
	{ district: 'Portalegre', city: 'Portalegre' },

	{ district: 'Porto', city: 'Ermesinde' },
	{ district: 'Porto', city: 'Espinho' },
	{ district: 'Porto', city: 'Felgueiras' },
	{ district: 'Porto', city: 'Gondomar' },
	{ district: 'Porto', city: 'Lixa' },
	{ district: 'Porto', city: 'Lordelo' },
	{ district: 'Porto', city: 'Maia' },
	{ district: 'Porto', city: 'Matosinhos' },
	{ district: 'Porto', city: 'Paços de Ferreira' },
	{ district: 'Porto', city: 'Paredes' },
	{ district: 'Porto', city: 'Penafiel' },
	{ district: 'Porto', city: 'Porto' },
	{ district: 'Porto', city: 'Póvoa de Varzim' },
	{ district: 'Porto', city: 'Rebordosa' },
	{ district: 'Porto', city: 'Rio Tinto' },
	{ district: 'Porto', city: 'Trofa' },
	{ district: 'Porto', city: 'Valbom' },
	{ district: 'Porto', city: 'Valongo' },
	{ district: 'Porto', city: 'Vila do Conde' },
	{ district: 'Porto', city: 'Vila Nova de Gaia' },
	{ district: 'Porto', city: 'São João da Madeira' },
	{ district: 'Porto', city: 'Senhora da Hora' },

	{ district: 'Santarém', city: 'Abrantes' },
	{ district: 'Santarém', city: 'Almeirim' },
	{ district: 'Santarém', city: 'Cartaxo' },
	{ district: 'Santarém', city: 'Entroncamento' },
	{ district: 'Santarém', city: 'Fátima' },
	{ district: 'Santarém', city: 'Rio Maior' },
	{ district: 'Santarém', city: 'Santarém' },
	{ district: 'Santarém', city: 'Samora Correia' },
	{ district: 'Santarém', city: 'Torres Novas' },
	{ district: 'Santarém', city: 'Vila Nova da Barquinha' },

	{ district: 'Setúbal', city: 'Alcácer do Sal' },
	{ district: 'Setúbal', city: 'Almada' },
	{ district: 'Setúbal', city: 'Barreiro' },
	{ district: 'Setúbal', city: 'Costa da Caparica' },
	{ district: 'Setúbal', city: 'Moita' },
	{ district: 'Setúbal', city: 'Montijo' },
	{ district: 'Setúbal', city: 'Palmela' },
	{ district: 'Setúbal', city: 'Seixal' },
	{ district: 'Setúbal', city: 'Sesimbra' },
	{ district: 'Setúbal', city: 'Setúbal' },
	{ district: 'Setúbal', city: 'Sines' },
	{ district: 'Setúbal', city: 'Vila Nova de Santo André' },

	{ district: 'Viana do Castelo', city: 'Valença' },
	{ district: 'Viana do Castelo', city: 'Viana do Castelo' },
	{ district: 'Viana do Castelo', city: 'Vila Nova de Cerveira' },

	{ district: 'Vila Real', city: 'Chaves' },
	{ district: 'Vila Real', city: 'Peso da Régua' },
	{ district: 'Vila Real', city: 'Valpaços' },
	{ district: 'Vila Real', city: 'Vila Real' },

	{ district: 'Viseu', city: 'Lamego' },
	{ district: 'Viseu', city: 'Mangualde' },
	{ district: 'Viseu', city: 'Nelas' },
	{ district: 'Viseu', city: 'São Pedro do Sul' },
	{ district: 'Viseu', city: 'Tondela' },
	{ district: 'Viseu', city: 'Viseu' },

	{ district: 'Açores', city: 'Angra do Heroísmo' },
	{ district: 'Açores', city: 'Horta' },
	{ district: 'Açores', city: 'Lagoa' },
	{ district: 'Açores', city: 'Ponta Delgada' },
	{ district: 'Açores', city: 'Praia da Vitória' },
	{ district: 'Açores', city: 'Ribeira Grande' },

	{ district: 'Madeira', city: 'Câmara de Lobos' },
	{ district: 'Madeira', city: 'Caniço' },
	{ district: 'Madeira', city: 'Funchal' },
	{ district: 'Madeira', city: 'Machico' },
	{ district: 'Madeira', city: 'Santa Cruz' },
	{ district: 'Madeira', city: 'Santana' },
	{ district: 'Madeira', city: 'Vila Baleira' },
];
