export const PortugalDistricts = [
	{ distrito: 'Aveiro', cidade: 'Aveiro' },
	{ distrito: 'Aveiro', cidade: 'Águeda' },
	{ distrito: 'Aveiro', cidade: 'Albergaria-a-Velha' },
	{ distrito: 'Aveiro', cidade: 'Anadia' },
	{ distrito: 'Aveiro', cidade: 'Esmoriz' },
	{ distrito: 'Aveiro', cidade: 'Estarreja' },
	{ distrito: 'Aveiro', cidade: 'Gafanha da Nazaré' },
	{ distrito: 'Aveiro', cidade: 'Ílhavo' },
	{ distrito: 'Aveiro', cidade: 'Oliveira de Azeméis' },
	{ distrito: 'Aveiro', cidade: 'Oliveira do Bairro' },
	{ distrito: 'Aveiro', cidade: 'Ovar' },
	{ distrito: 'Aveiro', cidade: 'Santa Maria da Feira' },
	{ distrito: 'Aveiro', cidade: 'São João da Madeira' },
	{ distrito: 'Aveiro', cidade: 'Sever do Vouga' },
	{ distrito: 'Aveiro', cidade: 'Vale de Cambra' },

	{ distrito: 'Beja', cidade: 'Beja' },
	{ distrito: 'Beja', cidade: 'Castro Verde' },
	{ distrito: 'Beja', cidade: 'Moura' },
	{ distrito: 'Beja', cidade: 'Serpa' },

	{ distrito: 'Braga', cidade: 'Barcelos' },
	{ distrito: 'Braga', cidade: 'Braga' },
	{ distrito: 'Braga', cidade: 'Esposende' },
	{ distrito: 'Braga', cidade: 'Fafe' },
	{ distrito: 'Braga', cidade: 'Guimarães' },
	{ distrito: 'Braga', cidade: 'Vila Nova de Famalicão' },
	{ distrito: 'Braga', cidade: 'Vizela' },

	{ distrito: 'Bragança', cidade: 'Bragança' },
	{ distrito: 'Bragança', cidade: 'Macedo de Cavaleiros' },
	{ distrito: 'Bragança', cidade: 'Miranda do Douro' },
	{ distrito: 'Bragança', cidade: 'Mirandela' },
	{ distrito: 'Bragança', cidade: 'Mogadouro' },
	{ distrito: 'Bragança', cidade: 'Torre de Moncorvo' },
	{ distrito: 'Bragança', cidade: 'Vila Flor' },
	{ distrito: 'Bragança', cidade: 'Vila Nova de Foz Côa' },

	{ distrito: 'Castelo Branco', cidade: 'Castelo Branco' },
	{ distrito: 'Castelo Branco', cidade: 'Covilhã' },
	{ distrito: 'Castelo Branco', cidade: 'Fundão' },
	{ distrito: 'Castelo Branco', cidade: 'Sertã' },

	{ distrito: 'Coimbra', cidade: 'Arganil' },
	{ distrito: 'Coimbra', cidade: 'Cantanhede' },
	{ distrito: 'Coimbra', cidade: 'Coimbra' },
	{ distrito: 'Coimbra', cidade: 'Figueira da Foz' },
	{ distrito: 'Coimbra', cidade: 'Lousã' },
	{ distrito: 'Coimbra', cidade: 'Mealhada' },
	{ distrito: 'Coimbra', cidade: 'Miranda do Corvo' },
	{ distrito: 'Coimbra', cidade: 'Oliveira do Hospital' },
	{ distrito: 'Coimbra', cidade: 'Pampilhosa da Serra' },
	{ distrito: 'Coimbra', cidade: 'Penacova' },
	{ distrito: 'Coimbra', cidade: 'Penela' },
	{ distrito: 'Coimbra', cidade: 'Pombal' },
	{ distrito: 'Coimbra', cidade: 'Soure' },

	{ distrito: 'Évora', cidade: 'Borba' },
	{ distrito: 'Évora', cidade: 'Estremoz' },
	{ distrito: 'Évora', cidade: 'Évora' },
	{ distrito: 'Évora', cidade: 'Montemor-o-Novo' },
	{ distrito: 'Évora', cidade: 'Reguengos de Monsaraz' },
	{ distrito: 'Évora', cidade: 'Vendas Novas' },
	{ distrito: 'Évora', cidade: 'Vila Viçosa' },

	{ distrito: 'Faro', cidade: 'Albufeira' },
	{ distrito: 'Faro', cidade: 'Faro' },
	{ distrito: 'Faro', cidade: 'Lagoa' },
	{ distrito: 'Faro', cidade: 'Lagos' },
	{ distrito: 'Faro', cidade: 'Loulé' },
	{ distrito: 'Faro', cidade: 'Olhão' },
	{ distrito: 'Faro', cidade: 'Portimão' },
	{ distrito: 'Faro', cidade: 'Quarteira' },
	{ distrito: 'Faro', cidade: 'Silves' },
	{ distrito: 'Faro', cidade: 'Tavira' },
	{ distrito: 'Faro', cidade: 'Vila Real de Santo António' },

	{ distrito: 'Guarda', cidade: 'Gouveia' },
	{ distrito: 'Guarda', cidade: 'Guarda' },
	{ distrito: 'Guarda', cidade: 'Mêda' },
	{ distrito: 'Guarda', cidade: 'Pinhel' },
	{ distrito: 'Guarda', cidade: 'Sabugal' },
	{ distrito: 'Guarda', cidade: 'Seia' },
	{ distrito: 'Guarda', cidade: 'Trancoso' },

	{ distrito: 'Leiria', cidade: 'Alcobaça' },
	{ distrito: 'Leiria', cidade: 'Batalha' },
	{ distrito: 'Leiria', cidade: 'Caldas da Rainha' },
	{ distrito: 'Leiria', cidade: 'Leiria' },
	{ distrito: 'Leiria', cidade: 'Marinha Grande' },
	{ distrito: 'Leiria', cidade: 'Nazaré' },
	{ distrito: 'Leiria', cidade: 'Pedrógão Grande' },
	{ distrito: 'Leiria', cidade: 'Peniche' },
	{ distrito: 'Leiria', cidade: 'Pombal' },
	{ distrito: 'Leiria', cidade: 'Porto de Mós' },
	{ distrito: 'Leiria', cidade: 'Tomar' },

	{ distrito: 'Lisboa', cidade: 'Agualva-Cacém' },
	{ distrito: 'Lisboa', cidade: 'Alverca do Ribatejo' },
	{ distrito: 'Lisboa', cidade: 'Amadora' },
	{ distrito: 'Lisboa', cidade: 'Lisboa' },
	{ distrito: 'Lisboa', cidade: 'Loures' },
	{ distrito: 'Lisboa', cidade: 'Odivelas' },
	{ distrito: 'Lisboa', cidade: 'Oeiras' },
	{ distrito: 'Lisboa', cidade: 'Póvoa de Santa Iria' },
	{ distrito: 'Lisboa', cidade: 'Queluz' },
	{ distrito: 'Lisboa', cidade: 'Sacavém' },
	{ distrito: 'Lisboa', cidade: 'Sintra' },
	{ distrito: 'Lisboa', cidade: 'Vila Franca de Xira' },

	{ distrito: 'Portalegre', cidade: 'Campo Maior' },
	{ distrito: 'Portalegre', cidade: 'Elvas' },
	{ distrito: 'Portalegre', cidade: 'Ponte de Sor' },
	{ distrito: 'Portalegre', cidade: 'Portalegre' },

	{ distrito: 'Porto', cidade: 'Ermesinde' },
	{ distrito: 'Porto', cidade: 'Espinho' },
	{ distrito: 'Porto', cidade: 'Felgueiras' },
	{ distrito: 'Porto', cidade: 'Gondomar' },
	{ distrito: 'Porto', cidade: 'Lixa' },
	{ distrito: 'Porto', cidade: 'Lordelo' },
	{ distrito: 'Porto', cidade: 'Maia' },
	{ distrito: 'Porto', cidade: 'Matosinhos' },
	{ distrito: 'Porto', cidade: 'Paços de Ferreira' },
	{ distrito: 'Porto', cidade: 'Paredes' },
	{ distrito: 'Porto', cidade: 'Penafiel' },
	{ distrito: 'Porto', cidade: 'Porto' },
	{ distrito: 'Porto', cidade: 'Póvoa de Varzim' },
	{ distrito: 'Porto', cidade: 'Rebordosa' },
	{ distrito: 'Porto', cidade: 'Rio Tinto' },
	{ distrito: 'Porto', cidade: 'Trofa' },
	{ distrito: 'Porto', cidade: 'Valbom' },
	{ distrito: 'Porto', cidade: 'Valongo' },
	{ distrito: 'Porto', cidade: 'Vila do Conde' },
	{ distrito: 'Porto', cidade: 'Vila Nova de Gaia' },
	{ distrito: 'Porto', cidade: 'São João da Madeira' },
	{ distrito: 'Porto', cidade: 'Senhora da Hora' },

	{ distrito: 'Santarém', cidade: 'Abrantes' },
	{ distrito: 'Santarém', cidade: 'Almeirim' },
	{ distrito: 'Santarém', cidade: 'Cartaxo' },
	{ distrito: 'Santarém', cidade: 'Entroncamento' },
	{ distrito: 'Santarém', cidade: 'Fátima' },
	{ distrito: 'Santarém', cidade: 'Rio Maior' },
	{ distrito: 'Santarém', cidade: 'Santarém' },
	{ distrito: 'Santarém', cidade: 'Samora Correia' },
	{ distrito: 'Santarém', cidade: 'Torres Novas' },
	{ distrito: 'Santarém', cidade: 'Vila Nova da Barquinha' },

	{ distrito: 'Setúbal', cidade: 'Alcácer do Sal' },
	{ distrito: 'Setúbal', cidade: 'Almada' },
	{ distrito: 'Setúbal', cidade: 'Barreiro' },
	{ distrito: 'Setúbal', cidade: 'Costa da Caparica' },
	{ distrito: 'Setúbal', cidade: 'Moita' },
	{ distrito: 'Setúbal', cidade: 'Montijo' },
	{ distrito: 'Setúbal', cidade: 'Palmela' },
	{ distrito: 'Setúbal', cidade: 'Seixal' },
	{ distrito: 'Setúbal', cidade: 'Sesimbra' },
	{ distrito: 'Setúbal', cidade: 'Setúbal' },
	{ distrito: 'Setúbal', cidade: 'Sines' },
	{ distrito: 'Setúbal', cidade: 'Vila Nova de Santo André' },

	{ distrito: 'Viana do Castelo', cidade: 'Valença' },
	{ distrito: 'Viana do Castelo', cidade: 'Viana do Castelo' },
	{ distrito: 'Viana do Castelo', cidade: 'Vila Nova de Cerveira' },

	{ distrito: 'Vila Real', cidade: 'Chaves' },
	{ distrito: 'Vila Real', cidade: 'Peso da Régua' },
	{ distrito: 'Vila Real', cidade: 'Valpaços' },
	{ distrito: 'Vila Real', cidade: 'Vila Real' },

	{ distrito: 'Viseu', cidade: 'Lamego' },
	{ distrito: 'Viseu', cidade: 'Mangualde' },
	{ distrito: 'Viseu', cidade: 'Nelas' },
	{ distrito: 'Viseu', cidade: 'São Pedro do Sul' },
	{ distrito: 'Viseu', cidade: 'Tondela' },
	{ distrito: 'Viseu', cidade: 'Viseu' },

	{ distrito: 'Açores', cidade: 'Angra do Heroísmo' },
	{ distrito: 'Açores', cidade: 'Horta' },
	{ distrito: 'Açores', cidade: 'Lagoa' },
	{ distrito: 'Açores', cidade: 'Ponta Delgada' },
	{ distrito: 'Açores', cidade: 'Praia da Vitória' },
	{ distrito: 'Açores', cidade: 'Ribeira Grande' },

	{ distrito: 'Madeira', cidade: 'Câmara de Lobos' },
	{ distrito: 'Madeira', cidade: 'Caniço' },
	{ distrito: 'Madeira', cidade: 'Funchal' },
	{ distrito: 'Madeira', cidade: 'Machico' },
	{ distrito: 'Madeira', cidade: 'Santa Cruz' },
	{ distrito: 'Madeira', cidade: 'Santana' },
	{ distrito: 'Madeira', cidade: 'Vila Baleira' },
];
