/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125publicRouteRouteImport } from './routes/{-$locale}/(public)/route'
import { Route as Char123LocaleChar125publicIndexRouteImport } from './routes/{-$locale}/(public)/index'
import { Route as Char123LocaleChar125publicLoginRouteImport } from './routes/{-$locale}/(public)/login'
import { Route as Char123LocaleChar125adminDashboardRouteImport } from './routes/{-$locale}/(admin)/dashboard'
import { Route as Char123LocaleChar125publicEscortsIndexRouteImport } from './routes/{-$locale}/(public)/escorts.index'
import { Route as Char123LocaleChar125adminDashboardIndexRouteImport } from './routes/{-$locale}/(admin)/dashboard.index'
import { Route as Char123LocaleChar125adminDashboardSettingsRouteImport } from './routes/{-$locale}/(admin)/dashboard.settings'
import { Route as Char123LocaleChar125adminDashboardMyAccountRouteImport } from './routes/{-$locale}/(admin)/dashboard.my-account'
import { Route as Char123LocaleChar125adminDashboardAdvertsRouteImport } from './routes/{-$locale}/(admin)/dashboard.adverts'
import { Route as Char123LocaleChar125publicEscortsCountryIndexRouteImport } from './routes/{-$locale}/(public)/escorts.$country.index'
import { Route as Char123LocaleChar125publicEscortsCountrySlugIndexRouteImport } from './routes/{-$locale}/(public)/escorts.$country.$slug.index'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api.auth.$'

const rootServerRouteImport = createServerRootRoute()

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125publicRouteRoute =
  Char123LocaleChar125publicRouteRouteImport.update({
    id: '/(public)',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125publicIndexRoute =
  Char123LocaleChar125publicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125publicRouteRoute,
  } as any)
const Char123LocaleChar125publicLoginRoute =
  Char123LocaleChar125publicLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => Char123LocaleChar125publicRouteRoute,
  } as any)
const Char123LocaleChar125adminDashboardRoute =
  Char123LocaleChar125adminDashboardRouteImport.update({
    id: '/(admin)/dashboard',
    path: '/dashboard',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125publicEscortsIndexRoute =
  Char123LocaleChar125publicEscortsIndexRouteImport.update({
    id: '/escorts/',
    path: '/escorts/',
    getParentRoute: () => Char123LocaleChar125publicRouteRoute,
  } as any)
const Char123LocaleChar125adminDashboardIndexRoute =
  Char123LocaleChar125adminDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125adminDashboardRoute,
  } as any)
const Char123LocaleChar125adminDashboardSettingsRoute =
  Char123LocaleChar125adminDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => Char123LocaleChar125adminDashboardRoute,
  } as any)
const Char123LocaleChar125adminDashboardMyAccountRoute =
  Char123LocaleChar125adminDashboardMyAccountRouteImport.update({
    id: '/my-account',
    path: '/my-account',
    getParentRoute: () => Char123LocaleChar125adminDashboardRoute,
  } as any)
const Char123LocaleChar125adminDashboardAdvertsRoute =
  Char123LocaleChar125adminDashboardAdvertsRouteImport.update({
    id: '/adverts',
    path: '/adverts',
    getParentRoute: () => Char123LocaleChar125adminDashboardRoute,
  } as any)
const Char123LocaleChar125publicEscortsCountryIndexRoute =
  Char123LocaleChar125publicEscortsCountryIndexRouteImport.update({
    id: '/escorts/$country/',
    path: '/escorts/$country/',
    getParentRoute: () => Char123LocaleChar125publicRouteRoute,
  } as any)
const Char123LocaleChar125publicEscortsCountrySlugIndexRoute =
  Char123LocaleChar125publicEscortsCountrySlugIndexRouteImport.update({
    id: '/escorts/$country/$slug/',
    path: '/escorts/$country/$slug/',
    getParentRoute: () => Char123LocaleChar125publicRouteRoute,
  } as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125publicIndexRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125adminDashboardRouteWithChildren
  '/{-$locale}/login': typeof Char123LocaleChar125publicLoginRoute
  '/{-$locale}/dashboard/adverts': typeof Char123LocaleChar125adminDashboardAdvertsRoute
  '/{-$locale}/dashboard/my-account': typeof Char123LocaleChar125adminDashboardMyAccountRoute
  '/{-$locale}/dashboard/settings': typeof Char123LocaleChar125adminDashboardSettingsRoute
  '/{-$locale}/dashboard/': typeof Char123LocaleChar125adminDashboardIndexRoute
  '/{-$locale}/escorts': typeof Char123LocaleChar125publicEscortsIndexRoute
  '/{-$locale}/escorts/$country': typeof Char123LocaleChar125publicEscortsCountryIndexRoute
  '/{-$locale}/escorts/$country/$slug': typeof Char123LocaleChar125publicEscortsCountrySlugIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/login': typeof Char123LocaleChar125publicLoginRoute
  '/{-$locale}': typeof Char123LocaleChar125publicIndexRoute
  '/{-$locale}/dashboard/adverts': typeof Char123LocaleChar125adminDashboardAdvertsRoute
  '/{-$locale}/dashboard/my-account': typeof Char123LocaleChar125adminDashboardMyAccountRoute
  '/{-$locale}/dashboard/settings': typeof Char123LocaleChar125adminDashboardSettingsRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125adminDashboardIndexRoute
  '/{-$locale}/escorts': typeof Char123LocaleChar125publicEscortsIndexRoute
  '/{-$locale}/escorts/$country': typeof Char123LocaleChar125publicEscortsCountryIndexRoute
  '/{-$locale}/escorts/$country/$slug': typeof Char123LocaleChar125publicEscortsCountrySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/(public)': typeof Char123LocaleChar125publicRouteRouteWithChildren
  '/{-$locale}/(admin)/dashboard': typeof Char123LocaleChar125adminDashboardRouteWithChildren
  '/{-$locale}/(public)/login': typeof Char123LocaleChar125publicLoginRoute
  '/{-$locale}/(public)/': typeof Char123LocaleChar125publicIndexRoute
  '/{-$locale}/(admin)/dashboard/adverts': typeof Char123LocaleChar125adminDashboardAdvertsRoute
  '/{-$locale}/(admin)/dashboard/my-account': typeof Char123LocaleChar125adminDashboardMyAccountRoute
  '/{-$locale}/(admin)/dashboard/settings': typeof Char123LocaleChar125adminDashboardSettingsRoute
  '/{-$locale}/(admin)/dashboard/': typeof Char123LocaleChar125adminDashboardIndexRoute
  '/{-$locale}/(public)/escorts/': typeof Char123LocaleChar125publicEscortsIndexRoute
  '/{-$locale}/(public)/escorts/$country/': typeof Char123LocaleChar125publicEscortsCountryIndexRoute
  '/{-$locale}/(public)/escorts/$country/$slug/': typeof Char123LocaleChar125publicEscortsCountrySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/login'
    | '/{-$locale}/dashboard/adverts'
    | '/{-$locale}/dashboard/my-account'
    | '/{-$locale}/dashboard/settings'
    | '/{-$locale}/dashboard/'
    | '/{-$locale}/escorts'
    | '/{-$locale}/escorts/$country'
    | '/{-$locale}/escorts/$country/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/login'
    | '/{-$locale}'
    | '/{-$locale}/dashboard/adverts'
    | '/{-$locale}/dashboard/my-account'
    | '/{-$locale}/dashboard/settings'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/escorts'
    | '/{-$locale}/escorts/$country'
    | '/{-$locale}/escorts/$country/$slug'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/(public)'
    | '/{-$locale}/(admin)/dashboard'
    | '/{-$locale}/(public)/login'
    | '/{-$locale}/(public)/'
    | '/{-$locale}/(admin)/dashboard/adverts'
    | '/{-$locale}/(admin)/dashboard/my-account'
    | '/{-$locale}/(admin)/dashboard/settings'
    | '/{-$locale}/(admin)/dashboard/'
    | '/{-$locale}/(public)/escorts/'
    | '/{-$locale}/(public)/escorts/$country/'
    | '/{-$locale}/(public)/escorts/$country/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/(public)': {
      id: '/{-$locale}/(public)'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125publicRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(public)/': {
      id: '/{-$locale}/(public)/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125publicIndexRouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
    '/{-$locale}/(public)/login': {
      id: '/{-$locale}/(public)/login'
      path: '/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125publicLoginRouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
    '/{-$locale}/(admin)/dashboard': {
      id: '/{-$locale}/(admin)/dashboard'
      path: '/dashboard'
      fullPath: '/{-$locale}/dashboard'
      preLoaderRoute: typeof Char123LocaleChar125adminDashboardRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(public)/escorts/': {
      id: '/{-$locale}/(public)/escorts/'
      path: '/escorts'
      fullPath: '/{-$locale}/escorts'
      preLoaderRoute: typeof Char123LocaleChar125publicEscortsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
    '/{-$locale}/(admin)/dashboard/': {
      id: '/{-$locale}/(admin)/dashboard/'
      path: '/'
      fullPath: '/{-$locale}/dashboard/'
      preLoaderRoute: typeof Char123LocaleChar125adminDashboardIndexRouteImport
      parentRoute: typeof Char123LocaleChar125adminDashboardRoute
    }
    '/{-$locale}/(admin)/dashboard/settings': {
      id: '/{-$locale}/(admin)/dashboard/settings'
      path: '/settings'
      fullPath: '/{-$locale}/dashboard/settings'
      preLoaderRoute: typeof Char123LocaleChar125adminDashboardSettingsRouteImport
      parentRoute: typeof Char123LocaleChar125adminDashboardRoute
    }
    '/{-$locale}/(admin)/dashboard/my-account': {
      id: '/{-$locale}/(admin)/dashboard/my-account'
      path: '/my-account'
      fullPath: '/{-$locale}/dashboard/my-account'
      preLoaderRoute: typeof Char123LocaleChar125adminDashboardMyAccountRouteImport
      parentRoute: typeof Char123LocaleChar125adminDashboardRoute
    }
    '/{-$locale}/(admin)/dashboard/adverts': {
      id: '/{-$locale}/(admin)/dashboard/adverts'
      path: '/adverts'
      fullPath: '/{-$locale}/dashboard/adverts'
      preLoaderRoute: typeof Char123LocaleChar125adminDashboardAdvertsRouteImport
      parentRoute: typeof Char123LocaleChar125adminDashboardRoute
    }
    '/{-$locale}/(public)/escorts/$country/': {
      id: '/{-$locale}/(public)/escorts/$country/'
      path: '/escorts/$country'
      fullPath: '/{-$locale}/escorts/$country'
      preLoaderRoute: typeof Char123LocaleChar125publicEscortsCountryIndexRouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
    '/{-$locale}/(public)/escorts/$country/$slug/': {
      id: '/{-$locale}/(public)/escorts/$country/$slug/'
      path: '/escorts/$country/$slug'
      fullPath: '/{-$locale}/escorts/$country/$slug'
      preLoaderRoute: typeof Char123LocaleChar125publicEscortsCountrySlugIndexRouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface Char123LocaleChar125publicRouteRouteChildren {
  Char123LocaleChar125publicLoginRoute: typeof Char123LocaleChar125publicLoginRoute
  Char123LocaleChar125publicIndexRoute: typeof Char123LocaleChar125publicIndexRoute
  Char123LocaleChar125publicEscortsIndexRoute: typeof Char123LocaleChar125publicEscortsIndexRoute
  Char123LocaleChar125publicEscortsCountryIndexRoute: typeof Char123LocaleChar125publicEscortsCountryIndexRoute
  Char123LocaleChar125publicEscortsCountrySlugIndexRoute: typeof Char123LocaleChar125publicEscortsCountrySlugIndexRoute
}

const Char123LocaleChar125publicRouteRouteChildren: Char123LocaleChar125publicRouteRouteChildren =
  {
    Char123LocaleChar125publicLoginRoute: Char123LocaleChar125publicLoginRoute,
    Char123LocaleChar125publicIndexRoute: Char123LocaleChar125publicIndexRoute,
    Char123LocaleChar125publicEscortsIndexRoute:
      Char123LocaleChar125publicEscortsIndexRoute,
    Char123LocaleChar125publicEscortsCountryIndexRoute:
      Char123LocaleChar125publicEscortsCountryIndexRoute,
    Char123LocaleChar125publicEscortsCountrySlugIndexRoute:
      Char123LocaleChar125publicEscortsCountrySlugIndexRoute,
  }

const Char123LocaleChar125publicRouteRouteWithChildren =
  Char123LocaleChar125publicRouteRoute._addFileChildren(
    Char123LocaleChar125publicRouteRouteChildren,
  )

interface Char123LocaleChar125adminDashboardRouteChildren {
  Char123LocaleChar125adminDashboardAdvertsRoute: typeof Char123LocaleChar125adminDashboardAdvertsRoute
  Char123LocaleChar125adminDashboardMyAccountRoute: typeof Char123LocaleChar125adminDashboardMyAccountRoute
  Char123LocaleChar125adminDashboardSettingsRoute: typeof Char123LocaleChar125adminDashboardSettingsRoute
  Char123LocaleChar125adminDashboardIndexRoute: typeof Char123LocaleChar125adminDashboardIndexRoute
}

const Char123LocaleChar125adminDashboardRouteChildren: Char123LocaleChar125adminDashboardRouteChildren =
  {
    Char123LocaleChar125adminDashboardAdvertsRoute:
      Char123LocaleChar125adminDashboardAdvertsRoute,
    Char123LocaleChar125adminDashboardMyAccountRoute:
      Char123LocaleChar125adminDashboardMyAccountRoute,
    Char123LocaleChar125adminDashboardSettingsRoute:
      Char123LocaleChar125adminDashboardSettingsRoute,
    Char123LocaleChar125adminDashboardIndexRoute:
      Char123LocaleChar125adminDashboardIndexRoute,
  }

const Char123LocaleChar125adminDashboardRouteWithChildren =
  Char123LocaleChar125adminDashboardRoute._addFileChildren(
    Char123LocaleChar125adminDashboardRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125publicRouteRoute: typeof Char123LocaleChar125publicRouteRouteWithChildren
  Char123LocaleChar125adminDashboardRoute: typeof Char123LocaleChar125adminDashboardRouteWithChildren
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125publicRouteRoute:
      Char123LocaleChar125publicRouteRouteWithChildren,
    Char123LocaleChar125adminDashboardRoute:
      Char123LocaleChar125adminDashboardRouteWithChildren,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
