/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as DashboardSlugRouteImport } from './routes/dashboard/$slug'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as publicEscortsIndexRouteImport } from './routes/(public)/escorts.index'
import { Route as publicEscortsSlugRouteImport } from './routes/(public)/escorts.$slug'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const DashboardSlugRoute = DashboardSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicEscortsIndexRoute = publicEscortsIndexRouteImport.update({
  id: '/escorts/',
  path: '/escorts/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicEscortsSlugRoute = publicEscortsSlugRouteImport.update({
  id: '/escorts/$slug',
  path: '/escorts/$slug',
  getParentRoute: () => publicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/dashboard/$slug': typeof DashboardSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/escorts/$slug': typeof publicEscortsSlugRoute
  '/escorts': typeof publicEscortsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/dashboard/$slug': typeof DashboardSlugRoute
  '/': typeof publicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/escorts/$slug': typeof publicEscortsSlugRoute
  '/escorts': typeof publicEscortsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/dashboard/$slug': typeof DashboardSlugRoute
  '/(public)/': typeof publicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/(public)/escorts/$slug': typeof publicEscortsSlugRoute
  '/(public)/escorts/': typeof publicEscortsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/$slug'
    | '/dashboard/'
    | '/escorts/$slug'
    | '/escorts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard/$slug'
    | '/'
    | '/dashboard'
    | '/escorts/$slug'
    | '/escorts'
  id:
    | '__root__'
    | '/(public)'
    | '/dashboard'
    | '/(auth)/login'
    | '/dashboard/$slug'
    | '/(public)/'
    | '/dashboard/'
    | '/(public)/escorts/$slug'
    | '/(public)/escorts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/dashboard/$slug': {
      id: '/dashboard/$slug'
      path: '/$slug'
      fullPath: '/dashboard/$slug'
      preLoaderRoute: typeof DashboardSlugRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/escorts/': {
      id: '/(public)/escorts/'
      path: '/escorts'
      fullPath: '/escorts'
      preLoaderRoute: typeof publicEscortsIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/escorts/$slug': {
      id: '/(public)/escorts/$slug'
      path: '/escorts/$slug'
      fullPath: '/escorts/$slug'
      preLoaderRoute: typeof publicEscortsSlugRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicEscortsSlugRoute: typeof publicEscortsSlugRoute
  publicEscortsIndexRoute: typeof publicEscortsIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicEscortsSlugRoute: publicEscortsSlugRoute,
  publicEscortsIndexRoute: publicEscortsIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardSlugRoute: typeof DashboardSlugRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSlugRoute: DashboardSlugRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
