/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125publicRouteRouteImport } from './routes/{-$locale}/(public)/route'
import { Route as Char123LocaleChar125publicIndexRouteImport } from './routes/{-$locale}/(public)/index'
import { Route as Char123LocaleChar125publicTermsAndConditionsRouteImport } from './routes/{-$locale}/(public)/terms-and-conditions'
import { Route as Char123LocaleChar125publicSignInRouteImport } from './routes/{-$locale}/(public)/sign-in'
import { Route as Char123LocaleChar125publicResetPasswordRouteImport } from './routes/{-$locale}/(public)/reset-password'
import { Route as Char123LocaleChar125publicPrivacyPolicyRouteImport } from './routes/{-$locale}/(public)/privacy-policy'
import { Route as Char123LocaleChar125publicCookiePolicyRouteImport } from './routes/{-$locale}/(public)/cookie-policy'
import { Route as Char123LocaleChar125publicActivateRouteImport } from './routes/{-$locale}/(public)/activate'
import { Route as Char123LocaleChar125adminDashboardRouteImport } from './routes/{-$locale}/(admin)/dashboard'
import { Route as Char123LocaleChar125publicEscortsIndexRouteImport } from './routes/{-$locale}/(public)/escorts.index'
import { Route as Char123LocaleChar125adminDashboardIndexRouteImport } from './routes/{-$locale}/(admin)/dashboard.index'
import { Route as Char123LocaleChar125publicEscortsCountryRouteImport } from './routes/{-$locale}/(public)/escorts.$country'
import { Route as Char123LocaleChar125adminDashboardSettingsRouteImport } from './routes/{-$locale}/(admin)/dashboard.settings'
import { Route as Char123LocaleChar125adminDashboardReviewsRouteImport } from './routes/{-$locale}/(admin)/dashboard.reviews'
import { Route as Char123LocaleChar125adminDashboardProfileRouteImport } from './routes/{-$locale}/(admin)/dashboard.profile'
import { Route as Char123LocaleChar125adminDashboardMyAccountRouteImport } from './routes/{-$locale}/(admin)/dashboard.my-account'
import { Route as Char123LocaleChar125adminDashboardAdvertsRouteImport } from './routes/{-$locale}/(admin)/dashboard.adverts'
import { Route as Char123LocaleChar125publicEscortPublic_idChar123SlugChar125RouteImport } from './routes/{-$locale}/(public)/escort.$public_id.{-$slug}'
import { ServerRoute as ApiRpcSplatServerRouteImport } from './routes/api/rpc.$'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth.$'

const rootServerRouteImport = createServerRootRoute()

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125publicRouteRoute =
  Char123LocaleChar125publicRouteRouteImport.update({
    id: '/(public)',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125publicIndexRoute =
  Char123LocaleChar125publicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125publicRouteRoute,
  } as any)
const Char123LocaleChar125publicTermsAndConditionsRoute =
  Char123LocaleChar125publicTermsAndConditionsRouteImport.update({
    id: '/terms-and-conditions',
    path: '/terms-and-conditions',
    getParentRoute: () => Char123LocaleChar125publicRouteRoute,
  } as any)
const Char123LocaleChar125publicSignInRoute =
  Char123LocaleChar125publicSignInRouteImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => Char123LocaleChar125publicRouteRoute,
  } as any)
const Char123LocaleChar125publicResetPasswordRoute =
  Char123LocaleChar125publicResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => Char123LocaleChar125publicRouteRoute,
  } as any)
const Char123LocaleChar125publicPrivacyPolicyRoute =
  Char123LocaleChar125publicPrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => Char123LocaleChar125publicRouteRoute,
  } as any)
const Char123LocaleChar125publicCookiePolicyRoute =
  Char123LocaleChar125publicCookiePolicyRouteImport.update({
    id: '/cookie-policy',
    path: '/cookie-policy',
    getParentRoute: () => Char123LocaleChar125publicRouteRoute,
  } as any)
const Char123LocaleChar125publicActivateRoute =
  Char123LocaleChar125publicActivateRouteImport.update({
    id: '/activate',
    path: '/activate',
    getParentRoute: () => Char123LocaleChar125publicRouteRoute,
  } as any)
const Char123LocaleChar125adminDashboardRoute =
  Char123LocaleChar125adminDashboardRouteImport.update({
    id: '/(admin)/dashboard',
    path: '/dashboard',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125publicEscortsIndexRoute =
  Char123LocaleChar125publicEscortsIndexRouteImport.update({
    id: '/escorts/',
    path: '/escorts/',
    getParentRoute: () => Char123LocaleChar125publicRouteRoute,
  } as any)
const Char123LocaleChar125adminDashboardIndexRoute =
  Char123LocaleChar125adminDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125adminDashboardRoute,
  } as any)
const Char123LocaleChar125publicEscortsCountryRoute =
  Char123LocaleChar125publicEscortsCountryRouteImport.update({
    id: '/escorts/$country',
    path: '/escorts/$country',
    getParentRoute: () => Char123LocaleChar125publicRouteRoute,
  } as any)
const Char123LocaleChar125adminDashboardSettingsRoute =
  Char123LocaleChar125adminDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => Char123LocaleChar125adminDashboardRoute,
  } as any)
const Char123LocaleChar125adminDashboardReviewsRoute =
  Char123LocaleChar125adminDashboardReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => Char123LocaleChar125adminDashboardRoute,
  } as any)
const Char123LocaleChar125adminDashboardProfileRoute =
  Char123LocaleChar125adminDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => Char123LocaleChar125adminDashboardRoute,
  } as any)
const Char123LocaleChar125adminDashboardMyAccountRoute =
  Char123LocaleChar125adminDashboardMyAccountRouteImport.update({
    id: '/my-account',
    path: '/my-account',
    getParentRoute: () => Char123LocaleChar125adminDashboardRoute,
  } as any)
const Char123LocaleChar125adminDashboardAdvertsRoute =
  Char123LocaleChar125adminDashboardAdvertsRouteImport.update({
    id: '/adverts',
    path: '/adverts',
    getParentRoute: () => Char123LocaleChar125adminDashboardRoute,
  } as any)
const Char123LocaleChar125publicEscortPublic_idChar123SlugChar125Route =
  Char123LocaleChar125publicEscortPublic_idChar123SlugChar125RouteImport.update(
    {
      id: '/escort/$public_id/{-$slug}',
      path: '/escort/$public_id/{-$slug}',
      getParentRoute: () => Char123LocaleChar125publicRouteRoute,
    } as any,
  )
const ApiRpcSplatServerRoute = ApiRpcSplatServerRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125publicIndexRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125adminDashboardRouteWithChildren
  '/{-$locale}/activate': typeof Char123LocaleChar125publicActivateRoute
  '/{-$locale}/cookie-policy': typeof Char123LocaleChar125publicCookiePolicyRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125publicPrivacyPolicyRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125publicResetPasswordRoute
  '/{-$locale}/sign-in': typeof Char123LocaleChar125publicSignInRoute
  '/{-$locale}/terms-and-conditions': typeof Char123LocaleChar125publicTermsAndConditionsRoute
  '/{-$locale}/dashboard/adverts': typeof Char123LocaleChar125adminDashboardAdvertsRoute
  '/{-$locale}/dashboard/my-account': typeof Char123LocaleChar125adminDashboardMyAccountRoute
  '/{-$locale}/dashboard/profile': typeof Char123LocaleChar125adminDashboardProfileRoute
  '/{-$locale}/dashboard/reviews': typeof Char123LocaleChar125adminDashboardReviewsRoute
  '/{-$locale}/dashboard/settings': typeof Char123LocaleChar125adminDashboardSettingsRoute
  '/{-$locale}/escorts/$country': typeof Char123LocaleChar125publicEscortsCountryRoute
  '/{-$locale}/dashboard/': typeof Char123LocaleChar125adminDashboardIndexRoute
  '/{-$locale}/escorts': typeof Char123LocaleChar125publicEscortsIndexRoute
  '/{-$locale}/escort/$public_id/{-$slug}': typeof Char123LocaleChar125publicEscortPublic_idChar123SlugChar125Route
}
export interface FileRoutesByTo {
  '/{-$locale}/activate': typeof Char123LocaleChar125publicActivateRoute
  '/{-$locale}/cookie-policy': typeof Char123LocaleChar125publicCookiePolicyRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125publicPrivacyPolicyRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125publicResetPasswordRoute
  '/{-$locale}/sign-in': typeof Char123LocaleChar125publicSignInRoute
  '/{-$locale}/terms-and-conditions': typeof Char123LocaleChar125publicTermsAndConditionsRoute
  '/{-$locale}': typeof Char123LocaleChar125publicIndexRoute
  '/{-$locale}/dashboard/adverts': typeof Char123LocaleChar125adminDashboardAdvertsRoute
  '/{-$locale}/dashboard/my-account': typeof Char123LocaleChar125adminDashboardMyAccountRoute
  '/{-$locale}/dashboard/profile': typeof Char123LocaleChar125adminDashboardProfileRoute
  '/{-$locale}/dashboard/reviews': typeof Char123LocaleChar125adminDashboardReviewsRoute
  '/{-$locale}/dashboard/settings': typeof Char123LocaleChar125adminDashboardSettingsRoute
  '/{-$locale}/escorts/$country': typeof Char123LocaleChar125publicEscortsCountryRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125adminDashboardIndexRoute
  '/{-$locale}/escorts': typeof Char123LocaleChar125publicEscortsIndexRoute
  '/{-$locale}/escort/$public_id/{-$slug}': typeof Char123LocaleChar125publicEscortPublic_idChar123SlugChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/(public)': typeof Char123LocaleChar125publicRouteRouteWithChildren
  '/{-$locale}/(admin)/dashboard': typeof Char123LocaleChar125adminDashboardRouteWithChildren
  '/{-$locale}/(public)/activate': typeof Char123LocaleChar125publicActivateRoute
  '/{-$locale}/(public)/cookie-policy': typeof Char123LocaleChar125publicCookiePolicyRoute
  '/{-$locale}/(public)/privacy-policy': typeof Char123LocaleChar125publicPrivacyPolicyRoute
  '/{-$locale}/(public)/reset-password': typeof Char123LocaleChar125publicResetPasswordRoute
  '/{-$locale}/(public)/sign-in': typeof Char123LocaleChar125publicSignInRoute
  '/{-$locale}/(public)/terms-and-conditions': typeof Char123LocaleChar125publicTermsAndConditionsRoute
  '/{-$locale}/(public)/': typeof Char123LocaleChar125publicIndexRoute
  '/{-$locale}/(admin)/dashboard/adverts': typeof Char123LocaleChar125adminDashboardAdvertsRoute
  '/{-$locale}/(admin)/dashboard/my-account': typeof Char123LocaleChar125adminDashboardMyAccountRoute
  '/{-$locale}/(admin)/dashboard/profile': typeof Char123LocaleChar125adminDashboardProfileRoute
  '/{-$locale}/(admin)/dashboard/reviews': typeof Char123LocaleChar125adminDashboardReviewsRoute
  '/{-$locale}/(admin)/dashboard/settings': typeof Char123LocaleChar125adminDashboardSettingsRoute
  '/{-$locale}/(public)/escorts/$country': typeof Char123LocaleChar125publicEscortsCountryRoute
  '/{-$locale}/(admin)/dashboard/': typeof Char123LocaleChar125adminDashboardIndexRoute
  '/{-$locale}/(public)/escorts/': typeof Char123LocaleChar125publicEscortsIndexRoute
  '/{-$locale}/(public)/escort/$public_id/{-$slug}': typeof Char123LocaleChar125publicEscortPublic_idChar123SlugChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/activate'
    | '/{-$locale}/cookie-policy'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/sign-in'
    | '/{-$locale}/terms-and-conditions'
    | '/{-$locale}/dashboard/adverts'
    | '/{-$locale}/dashboard/my-account'
    | '/{-$locale}/dashboard/profile'
    | '/{-$locale}/dashboard/reviews'
    | '/{-$locale}/dashboard/settings'
    | '/{-$locale}/escorts/$country'
    | '/{-$locale}/dashboard/'
    | '/{-$locale}/escorts'
    | '/{-$locale}/escort/$public_id/{-$slug}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/activate'
    | '/{-$locale}/cookie-policy'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/sign-in'
    | '/{-$locale}/terms-and-conditions'
    | '/{-$locale}'
    | '/{-$locale}/dashboard/adverts'
    | '/{-$locale}/dashboard/my-account'
    | '/{-$locale}/dashboard/profile'
    | '/{-$locale}/dashboard/reviews'
    | '/{-$locale}/dashboard/settings'
    | '/{-$locale}/escorts/$country'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/escorts'
    | '/{-$locale}/escort/$public_id/{-$slug}'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/(public)'
    | '/{-$locale}/(admin)/dashboard'
    | '/{-$locale}/(public)/activate'
    | '/{-$locale}/(public)/cookie-policy'
    | '/{-$locale}/(public)/privacy-policy'
    | '/{-$locale}/(public)/reset-password'
    | '/{-$locale}/(public)/sign-in'
    | '/{-$locale}/(public)/terms-and-conditions'
    | '/{-$locale}/(public)/'
    | '/{-$locale}/(admin)/dashboard/adverts'
    | '/{-$locale}/(admin)/dashboard/my-account'
    | '/{-$locale}/(admin)/dashboard/profile'
    | '/{-$locale}/(admin)/dashboard/reviews'
    | '/{-$locale}/(admin)/dashboard/settings'
    | '/{-$locale}/(public)/escorts/$country'
    | '/{-$locale}/(admin)/dashboard/'
    | '/{-$locale}/(public)/escorts/'
    | '/{-$locale}/(public)/escort/$public_id/{-$slug}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/rpc/$': typeof ApiRpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$' | '/api/rpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$' | '/api/rpc/$'
  id: '__root__' | '/api/auth/$' | '/api/rpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiRpcSplatServerRoute: typeof ApiRpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/(public)': {
      id: '/{-$locale}/(public)'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125publicRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(public)/': {
      id: '/{-$locale}/(public)/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125publicIndexRouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
    '/{-$locale}/(public)/terms-and-conditions': {
      id: '/{-$locale}/(public)/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/{-$locale}/terms-and-conditions'
      preLoaderRoute: typeof Char123LocaleChar125publicTermsAndConditionsRouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
    '/{-$locale}/(public)/sign-in': {
      id: '/{-$locale}/(public)/sign-in'
      path: '/sign-in'
      fullPath: '/{-$locale}/sign-in'
      preLoaderRoute: typeof Char123LocaleChar125publicSignInRouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
    '/{-$locale}/(public)/reset-password': {
      id: '/{-$locale}/(public)/reset-password'
      path: '/reset-password'
      fullPath: '/{-$locale}/reset-password'
      preLoaderRoute: typeof Char123LocaleChar125publicResetPasswordRouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
    '/{-$locale}/(public)/privacy-policy': {
      id: '/{-$locale}/(public)/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/{-$locale}/privacy-policy'
      preLoaderRoute: typeof Char123LocaleChar125publicPrivacyPolicyRouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
    '/{-$locale}/(public)/cookie-policy': {
      id: '/{-$locale}/(public)/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/{-$locale}/cookie-policy'
      preLoaderRoute: typeof Char123LocaleChar125publicCookiePolicyRouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
    '/{-$locale}/(public)/activate': {
      id: '/{-$locale}/(public)/activate'
      path: '/activate'
      fullPath: '/{-$locale}/activate'
      preLoaderRoute: typeof Char123LocaleChar125publicActivateRouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
    '/{-$locale}/(admin)/dashboard': {
      id: '/{-$locale}/(admin)/dashboard'
      path: '/dashboard'
      fullPath: '/{-$locale}/dashboard'
      preLoaderRoute: typeof Char123LocaleChar125adminDashboardRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(public)/escorts/': {
      id: '/{-$locale}/(public)/escorts/'
      path: '/escorts'
      fullPath: '/{-$locale}/escorts'
      preLoaderRoute: typeof Char123LocaleChar125publicEscortsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
    '/{-$locale}/(admin)/dashboard/': {
      id: '/{-$locale}/(admin)/dashboard/'
      path: '/'
      fullPath: '/{-$locale}/dashboard/'
      preLoaderRoute: typeof Char123LocaleChar125adminDashboardIndexRouteImport
      parentRoute: typeof Char123LocaleChar125adminDashboardRoute
    }
    '/{-$locale}/(public)/escorts/$country': {
      id: '/{-$locale}/(public)/escorts/$country'
      path: '/escorts/$country'
      fullPath: '/{-$locale}/escorts/$country'
      preLoaderRoute: typeof Char123LocaleChar125publicEscortsCountryRouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
    '/{-$locale}/(admin)/dashboard/settings': {
      id: '/{-$locale}/(admin)/dashboard/settings'
      path: '/settings'
      fullPath: '/{-$locale}/dashboard/settings'
      preLoaderRoute: typeof Char123LocaleChar125adminDashboardSettingsRouteImport
      parentRoute: typeof Char123LocaleChar125adminDashboardRoute
    }
    '/{-$locale}/(admin)/dashboard/reviews': {
      id: '/{-$locale}/(admin)/dashboard/reviews'
      path: '/reviews'
      fullPath: '/{-$locale}/dashboard/reviews'
      preLoaderRoute: typeof Char123LocaleChar125adminDashboardReviewsRouteImport
      parentRoute: typeof Char123LocaleChar125adminDashboardRoute
    }
    '/{-$locale}/(admin)/dashboard/profile': {
      id: '/{-$locale}/(admin)/dashboard/profile'
      path: '/profile'
      fullPath: '/{-$locale}/dashboard/profile'
      preLoaderRoute: typeof Char123LocaleChar125adminDashboardProfileRouteImport
      parentRoute: typeof Char123LocaleChar125adminDashboardRoute
    }
    '/{-$locale}/(admin)/dashboard/my-account': {
      id: '/{-$locale}/(admin)/dashboard/my-account'
      path: '/my-account'
      fullPath: '/{-$locale}/dashboard/my-account'
      preLoaderRoute: typeof Char123LocaleChar125adminDashboardMyAccountRouteImport
      parentRoute: typeof Char123LocaleChar125adminDashboardRoute
    }
    '/{-$locale}/(admin)/dashboard/adverts': {
      id: '/{-$locale}/(admin)/dashboard/adverts'
      path: '/adverts'
      fullPath: '/{-$locale}/dashboard/adverts'
      preLoaderRoute: typeof Char123LocaleChar125adminDashboardAdvertsRouteImport
      parentRoute: typeof Char123LocaleChar125adminDashboardRoute
    }
    '/{-$locale}/(public)/escort/$public_id/{-$slug}': {
      id: '/{-$locale}/(public)/escort/$public_id/{-$slug}'
      path: '/escort/$public_id/{-$slug}'
      fullPath: '/{-$locale}/escort/$public_id/{-$slug}'
      preLoaderRoute: typeof Char123LocaleChar125publicEscortPublic_idChar123SlugChar125RouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface Char123LocaleChar125publicRouteRouteChildren {
  Char123LocaleChar125publicActivateRoute: typeof Char123LocaleChar125publicActivateRoute
  Char123LocaleChar125publicCookiePolicyRoute: typeof Char123LocaleChar125publicCookiePolicyRoute
  Char123LocaleChar125publicPrivacyPolicyRoute: typeof Char123LocaleChar125publicPrivacyPolicyRoute
  Char123LocaleChar125publicResetPasswordRoute: typeof Char123LocaleChar125publicResetPasswordRoute
  Char123LocaleChar125publicSignInRoute: typeof Char123LocaleChar125publicSignInRoute
  Char123LocaleChar125publicTermsAndConditionsRoute: typeof Char123LocaleChar125publicTermsAndConditionsRoute
  Char123LocaleChar125publicIndexRoute: typeof Char123LocaleChar125publicIndexRoute
  Char123LocaleChar125publicEscortsCountryRoute: typeof Char123LocaleChar125publicEscortsCountryRoute
  Char123LocaleChar125publicEscortsIndexRoute: typeof Char123LocaleChar125publicEscortsIndexRoute
  Char123LocaleChar125publicEscortPublic_idChar123SlugChar125Route: typeof Char123LocaleChar125publicEscortPublic_idChar123SlugChar125Route
}

const Char123LocaleChar125publicRouteRouteChildren: Char123LocaleChar125publicRouteRouteChildren =
  {
    Char123LocaleChar125publicActivateRoute:
      Char123LocaleChar125publicActivateRoute,
    Char123LocaleChar125publicCookiePolicyRoute:
      Char123LocaleChar125publicCookiePolicyRoute,
    Char123LocaleChar125publicPrivacyPolicyRoute:
      Char123LocaleChar125publicPrivacyPolicyRoute,
    Char123LocaleChar125publicResetPasswordRoute:
      Char123LocaleChar125publicResetPasswordRoute,
    Char123LocaleChar125publicSignInRoute:
      Char123LocaleChar125publicSignInRoute,
    Char123LocaleChar125publicTermsAndConditionsRoute:
      Char123LocaleChar125publicTermsAndConditionsRoute,
    Char123LocaleChar125publicIndexRoute: Char123LocaleChar125publicIndexRoute,
    Char123LocaleChar125publicEscortsCountryRoute:
      Char123LocaleChar125publicEscortsCountryRoute,
    Char123LocaleChar125publicEscortsIndexRoute:
      Char123LocaleChar125publicEscortsIndexRoute,
    Char123LocaleChar125publicEscortPublic_idChar123SlugChar125Route:
      Char123LocaleChar125publicEscortPublic_idChar123SlugChar125Route,
  }

const Char123LocaleChar125publicRouteRouteWithChildren =
  Char123LocaleChar125publicRouteRoute._addFileChildren(
    Char123LocaleChar125publicRouteRouteChildren,
  )

interface Char123LocaleChar125adminDashboardRouteChildren {
  Char123LocaleChar125adminDashboardAdvertsRoute: typeof Char123LocaleChar125adminDashboardAdvertsRoute
  Char123LocaleChar125adminDashboardMyAccountRoute: typeof Char123LocaleChar125adminDashboardMyAccountRoute
  Char123LocaleChar125adminDashboardProfileRoute: typeof Char123LocaleChar125adminDashboardProfileRoute
  Char123LocaleChar125adminDashboardReviewsRoute: typeof Char123LocaleChar125adminDashboardReviewsRoute
  Char123LocaleChar125adminDashboardSettingsRoute: typeof Char123LocaleChar125adminDashboardSettingsRoute
  Char123LocaleChar125adminDashboardIndexRoute: typeof Char123LocaleChar125adminDashboardIndexRoute
}

const Char123LocaleChar125adminDashboardRouteChildren: Char123LocaleChar125adminDashboardRouteChildren =
  {
    Char123LocaleChar125adminDashboardAdvertsRoute:
      Char123LocaleChar125adminDashboardAdvertsRoute,
    Char123LocaleChar125adminDashboardMyAccountRoute:
      Char123LocaleChar125adminDashboardMyAccountRoute,
    Char123LocaleChar125adminDashboardProfileRoute:
      Char123LocaleChar125adminDashboardProfileRoute,
    Char123LocaleChar125adminDashboardReviewsRoute:
      Char123LocaleChar125adminDashboardReviewsRoute,
    Char123LocaleChar125adminDashboardSettingsRoute:
      Char123LocaleChar125adminDashboardSettingsRoute,
    Char123LocaleChar125adminDashboardIndexRoute:
      Char123LocaleChar125adminDashboardIndexRoute,
  }

const Char123LocaleChar125adminDashboardRouteWithChildren =
  Char123LocaleChar125adminDashboardRoute._addFileChildren(
    Char123LocaleChar125adminDashboardRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125publicRouteRoute: typeof Char123LocaleChar125publicRouteRouteWithChildren
  Char123LocaleChar125adminDashboardRoute: typeof Char123LocaleChar125adminDashboardRouteWithChildren
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125publicRouteRoute:
      Char123LocaleChar125publicRouteRouteWithChildren,
    Char123LocaleChar125adminDashboardRoute:
      Char123LocaleChar125adminDashboardRouteWithChildren,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiRpcSplatServerRoute: ApiRpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
